
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package backend.analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 8;
  public static final int PUNTOYCOMA = 3;
  public static final int IGUAL = 5;
  public static final int INTEGERVAL = 18;
  public static final int PARC = 12;
  public static final int ID = 19;
  public static final int PARA = 11;
  public static final int POR = 9;
  public static final int BOOLEAN = 14;
  public static final int COMA = 17;
  public static final int STRING = 15;
  public static final int EOF = 0;
  public static final int STRINGVAL = 20;
  public static final int DIV = 10;
  public static final int error = 1;
  public static final int SHORT = 4;
  public static final int DPUNTO = 2;
  public static final int INTEGER = 13;
  public static final int DOUBLEVAL = 21;
  public static final int VAR = 6;
  public static final int MAS = 7;
  public static final int DOUBLE = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DPUNTO",
  "PUNTOYCOMA",
  "SHORT",
  "IGUAL",
  "VAR",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "PARA",
  "PARC",
  "INTEGER",
  "BOOLEAN",
  "STRING",
  "DOUBLE",
  "COMA",
  "INTEGERVAL",
  "ID",
  "STRINGVAL",
  "DOUBLEVAL"
  };
}

